# docker-compose.yml for Dukascopy API WebSocket
version: '3.8' # Specify the Docker Compose file format version

services:
  dukascopy-api:
    image: ismailfer/dukascopy-api:latest # The Docker image to use
    container_name: dukascopy-api-websocket # A friendly name for your container
    restart: unless-stopped # Always restart the container unless it's explicitly stopped
    networks:
      - dukascopy_api_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`datafeed.opessemper.com`)
      - traefik.http.routers.n8n.entrypoints=https
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.tls.certresolver=letsencrypt
      - traefik.http.routers.n8n.middlewares=n8n@docker
      - traefik.http.middlewares.n8n.headers.SSLRedirect=true
      - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
      - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
      - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
      - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
      - traefik.http.middlewares.n8n.headers.SSLHost=opessemper.com
      - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.n8n.headers.STSPreload=true

networks:
  dukascopy_api_network:
    driver: bridge # Creates a default bridge network
